
/******************************************************************************\
| This file is auto generated by the build script. Do not modify manually.     |
|                                                                              |
| @author Krishna Raman                                                        |
| @since 6 Jun 2004                                                            |
|                                                                              |
\******************************************************************************/
package rtjdds.util;

public class BuildProperties{
	
    public static final String buildJvm = "jvm";
    
    public static final boolean dbgImmortal = true;
    public static final boolean dbgApplicationScope = true;
    public static final boolean dbgProperties = true;
    public static final boolean dbgAcceptor = true;

    public static final int dbgImmortalId = 0;
    public static final int dbgApplicationScopeId = 0;
    
    public static final int MEM_STAT_COUNT = 100;
    public static final int observeLastXPercent = 50;

    public static boolean dbgMap[] = new boolean[2];
    static{
        dbgMap[dbgImmortalId] = dbgImmortal;
        dbgMap[dbgApplicationScopeId] = dbgApplicationScope;
    }
}
        
