/* DO NOT EDIT THIS FILE - it was generated by jamaicah:
   -jni -d . -classpath ../../../classes jtools.time.HighResClock
*/

#ifndef _INCLUDED_JTOOLS_TIME_HIGHRESCLOCK_
#define _INCLUDED_JTOOLS_TIME_HIGHRESCLOCK_

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif


/* Class:     jtools.time.HighResClock
 * Method:    getTime
 * Signature: (Ljtools/time/HighResTime;)V */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT void JNICALL Java_jtools_time_HighResClock_getTime(JNIEnv *env, jclass c, jobject v0);


/* Class:     jtools.time.HighResClock
 * Method:    getClockTickCount
 * Signature: ()J */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jlong JNICALL Java_jtools_time_HighResClock_getClockTickCount(JNIEnv *env, jclass c);


/* Class:     jtools.time.HighResClock
 * Method:    getClockFrequency
 * Signature: ()F */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jfloat JNICALL Java_jtools_time_HighResClock_getClockFrequency(JNIEnv *env, jclass c);


/* Class:     jtools.time.HighResClock
 * Method:    getClockPeriod
 * Signature: ()D */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jdouble JNICALL Java_jtools_time_HighResClock_getClockPeriod(JNIEnv *env, jclass c);


#ifdef __cplusplus
}
#endif

#endif /* _INCLUDED_JTOOLS_TIME_HIGHRESCLOCK_ */

/* end of file */
